apiVersion: apps/v1
kind: Deployment
metadata:
  name: interop
spec:
  selector:
    matchLabels:
      app: interop
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: interop
    spec:
      containers:
      - name: interop
        image: acrakseu2des.azurecr.io/interoperabiliadad:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: interop-svc
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-ipv4: 172.18.5.240
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: interop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer