<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SSF.Interop.SIIFNacion.Worker</RootNamespace>
    <UserSecretsId>7c4e9b2a-8f1d-4c3e-9a5b-2d8e6f1a0c4d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cronos" Version="0.8.4" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.EventLog" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SSF.Interop.SIIFNacion.Application\SSF.Interop.SIIFNacion.Application.csproj" />
    <ProjectReference Include="..\SSF.Interop.SIIFNacion.Infrastructure\SSF.Interop.SIIFNacion.Infrastructure.csproj" />
    <ProjectReference Include="..\SSF.Interop.SIIFNacion.Persistence\SSF.Interop.SIIFNacion.Persistence.csproj" />
  </ItemGroup>

</Project>
